apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv1


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv2


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv3


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv4


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0005
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv5




---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0006
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv6




---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0007
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv7


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0008
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv8


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0009
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv9

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0010
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/azureuser/data/pv10




