#!/usr/bin/env bash

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

. "${GIT_ROOT}/.envrc"

cd "${GIT_ROOT}"

ENV_FILES="$(echo bin/settings/*.env bin/settings/kube/*.env)"

# TODO: We currently skip memory limits for development purposes

fissile build kube \
    --kube-output-dir="${GIT_ROOT}/kube" \
    --defaults-file="$(echo "${ENV_FILES}" | tr ' ' ,)" \
    --use-memory-limits=false \

# This is a small hack to make the output of make kube be compatible with K8s 1.6
perl -p -i -e 's@extensions/v1beta1@batch/v1@' kube/bosh-task/*.yml

sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/src/uaa-fissile-release/kube/bosh/mysql.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/consul.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/blobstore.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/etcd.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/diego-database.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/diego-cell.yml
sed -i'' '/annotations:/{N;d;}' ${GIT_ROOT}/kube/bosh/mysql.yml


sed -i'' 's/192.168.77.77/10.0.0.4/g'  ${GIT_ROOT}/kube/bosh/tcp-router.yml
sed -i'' 's/192.168.77.77/10.0.0.4/g'  ${GIT_ROOT}/kube/bosh/diego-access.yml
sed -i'' 's/192.168.77.77/10.0.0.4/g'  ${GIT_ROOT}/kube/bosh/router.yml
